In [223]:
#Data Cleaning
import pandas as pd
import numpy as np
data = pd.read_csv("diabetic_data.csv")

In [224]:
data.head(10)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,35754,82637451,Caucasian,Male,[50-60),?,2,1,2,3,...,No,Steady,No,No,No,No,No,No,Yes,>30
6,55842,84259809,Caucasian,Male,[60-70),?,3,1,2,4,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
7,63768,114882984,Caucasian,Male,[70-80),?,1,1,7,5,...,No,No,No,No,No,No,No,No,Yes,>30
8,12522,48330783,Caucasian,Female,[80-90),?,2,1,4,13,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,15738,63555939,Caucasian,Female,[90-100),?,3,3,4,12,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [225]:
data.shape

(101766, 50)

In [226]:
data.drop('encounter_id', axis=1, inplace=True)

In [227]:
data.head(10)

,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,8222157,Caucasian,Female,[0-10),?,6,25,1,1,?,...,No,No,No,No,No,No,No,No,No,NO
1,55629189,Caucasian,Female,[10-20),?,1,1,7,3,?,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,?,...,No,No,No,No,No,No,No,No,Yes,NO
3,82442376,Caucasian,Male,[30-40),?,1,1,7,2,?,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,42519267,Caucasian,Male,[40-50),?,1,1,7,1,?,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,82637451,Caucasian,Male,[50-60),?,2,1,2,3,?,...,No,Steady,No,No,No,No,No,No,Yes,>30
6,84259809,Caucasian,Male,[60-70),?,3,1,2,4,?,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
7,114882984,Caucasian,Male,[70-80),?,1,1,7,5,?,...,No,No,No,No,No,No,No,No,Yes,>30
8,48330783,Caucasian,Female,[80-90),?,2,1,4,13,?,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,63555939,Caucasian,Female,[90-100),?,3,3,4,12,?,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [228]:
print("Summary of Missing Value before operations")
print(data.isnull().sum())

Summary of Missing Value before operations
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [229]:
data.replace('?', np.nan, inplace=True)

In [230]:
print("\nSummary of missing values after operation:")
print(data.isnull().sum())

Summary of missing values after operation:
patient_nbr                     0
race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [231]:
data['readmitted'] = data['readmitted'].replace({'<30': 1, '>30': 0, 'NO': 0})
data['readmitted'] = data['readmitted'].astype('bool')
data.head(20)

,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,...,No,No,No,No,No,No,No,No,No,False
1,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,...,No,Up,No,No,No,No,No,Ch,Yes,False
2,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,...,No,No,No,No,No,No,No,No,Yes,False
3,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,...,No,Up,No,No,No,No,No,Ch,Yes,False
4,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,False
5,82637451,Caucasian,Male,[50-60),NaN,2,1,2,3,NaN,...,No,Steady,No,No,No,No,No,No,Yes,False
6,84259809,Caucasian,Male,[60-70),NaN,3,1,2,4,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,False
7,114882984,Caucasian,Male,[70-80),NaN,1,1,7,5,NaN,...,No,No,No,No,No,No,No,No,Yes,False
8,48330783,Caucasian,Female,[80-90),NaN,2,1,4,13,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,False
9,63555939,Caucasian,Female,[90-100),NaN,3,3,4,12,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,False
10,89869032,AfricanAmerican,Female,[40-50),NaN,1,1,7,9,NaN,...,No,Steady,No,No,No,No,No,No,Yes,False
11,77391171,AfricanAmerican,Male,[60-70),NaN,2,1,4,7,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,True
12,85504905,Caucasian,Female,[40-50),NaN,1,3,7,7,NaN,...,No,Down,No,No,No,No,No,Ch,Yes,True
13,77586282,Caucasian,Male,[80-90),NaN,1,6,7,10,NaN,...,No,Steady,No,No,No,No,No,No,Yes,False
14,49726791,AfricanAmerican,Female,[60-70),NaN,3,1,2,1,NaN,...,No,Steady,No,No,No,No,No,No,Yes,False
15,86328819,AfricanAmerican,Male,[60-70),NaN,1,3,7,12,NaN,...,No,Up,No,No,No,No,No,Ch,Yes,False
16,92519352,AfricanAmerican,Male,[50-60),NaN,1,1,7,4,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,True
17,108662661,Caucasian,Female,[50-60),NaN,1,1,7,3,NaN,...,No,No,No,No,No,No,No,No,Yes,False
18,107389323,AfricanAmerican,Male,[70-80),NaN,1,1,7,5,NaN,...,No,Steady,No,No,No,No,No,No,Yes,False
19,69422211,NaN,Male,[70-80),NaN,3,6,2,6,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,False

In [232]:
data.dtypes

patient_nbr                  int64
race                        object
gender                      object
age                         object
weight                      object
admission_type_id            int64
discharge_disposition_id     int64
admission_source_id          int64
time_in_hospital             int64
payer_code                  object
medical_specialty           object
num_lab_procedures           int64
num_procedures               int64
num_medications              int64
number_outpatient            int64
number_emergency             int64
number_inpatient             int64
diag_1                      object
diag_2                      object
diag_3                      object
number_diagnoses             int64
max_glu_serum               object
A1Cresult                   object
metformin                   object
repaglinide                 object
nateglinide                 object
chlorpropamide              object
glimepiride                 object
acetohexamide               object
glipizide                   object
glyburide                   object
tolbutamide                 object
pioglitazone                object
rosiglitazone               object
acarbose                    object
miglitol                    object
troglitazone                object
tolazamide                  object
examide                     object
citoglipton                 object
insulin                     object
glyburide-metformin         object
glipizide-metformin         object
glimepiride-pioglitazone    object
metformin-rosiglitazone     object
metformin-pioglitazone      object
change                      object
diabetesMed                 object
readmitted                    bool
dtype: object

In [233]:
# Calculate percentage of missing values for each column
missing_percentages = (data.isnull().sum() / len(data)) * 100

# Drop columns with more than 90% missing values
columns_to_drop = missing_percentages[missing_percentages > 90].index
data.drop(columns=columns_to_drop, inplace=True)

# Display the DataFrame after dropping columns
print("DataFrame after dropping columns with more than 90% missing values:")
data.head(10)

DataFrame after dropping columns with more than 90% missing values:

,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,8222157,Caucasian,Female,[0-10),6,25,1,1,NaN,Pediatrics-Endocrinology,...,No,No,No,No,No,No,No,No,No,False
1,55629189,Caucasian,Female,[10-20),1,1,7,3,NaN,NaN,...,No,Up,No,No,No,No,No,Ch,Yes,False
2,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,NaN,NaN,...,No,No,No,No,No,No,No,No,Yes,False
3,82442376,Caucasian,Male,[30-40),1,1,7,2,NaN,NaN,...,No,Up,No,No,No,No,No,Ch,Yes,False
4,42519267,Caucasian,Male,[40-50),1,1,7,1,NaN,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,False
5,82637451,Caucasian,Male,[50-60),2,1,2,3,NaN,NaN,...,No,Steady,No,No,No,No,No,No,Yes,False
6,84259809,Caucasian,Male,[60-70),3,1,2,4,NaN,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,False
7,114882984,Caucasian,Male,[70-80),1,1,7,5,NaN,NaN,...,No,No,No,No,No,No,No,No,Yes,False
8,48330783,Caucasian,Female,[80-90),2,1,4,13,NaN,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,False
9,63555939,Caucasian,Female,[90-100),3,3,4,12,NaN,InternalMedicine,...,No,Steady,No,No,No,No,No,Ch,Yes,False

In [234]:
data.shape

(101766, 47)

In [235]:
columns_to_deleted = ['repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 
                     'acetohexamide', 'tolbutamide', 'acarbose', 'miglitol', 
                     'troglitazone', 'tolazamide', 'examide', 'citoglipton', 
                     'glyburide-metformin', 'glipizide-metformin', 
                     'glimepiride-pioglitazone', 'metformin-rosiglitazone', 
                     'metformin-pioglitazone']

# Drop columns
data.drop(columns=columns_to_deleted, inplace=True)

# Display the DataSet after dropping columns
print("DataSet after dropping near zero-variance columns:")
data.head(10)

DataSet after dropping near zero-variance columns:

,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,...,A1Cresult,metformin,glipizide,glyburide,pioglitazone,rosiglitazone,insulin,change,diabetesMed,readmitted
0,8222157,Caucasian,Female,[0-10),6,25,1,1,NaN,Pediatrics-Endocrinology,...,NaN,No,No,No,No,No,No,No,No,False
1,55629189,Caucasian,Female,[10-20),1,1,7,3,NaN,NaN,...,NaN,No,No,No,No,No,Up,Ch,Yes,False
2,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,NaN,NaN,...,NaN,No,Steady,No,No,No,No,No,Yes,False
3,82442376,Caucasian,Male,[30-40),1,1,7,2,NaN,NaN,...,NaN,No,No,No,No,No,Up,Ch,Yes,False
4,42519267,Caucasian,Male,[40-50),1,1,7,1,NaN,NaN,...,NaN,No,Steady,No,No,No,Steady,Ch,Yes,False
5,82637451,Caucasian,Male,[50-60),2,1,2,3,NaN,NaN,...,NaN,No,No,No,No,No,Steady,No,Yes,False
6,84259809,Caucasian,Male,[60-70),3,1,2,4,NaN,NaN,...,NaN,Steady,No,No,No,No,Steady,Ch,Yes,False
7,114882984,Caucasian,Male,[70-80),1,1,7,5,NaN,NaN,...,NaN,No,No,Steady,No,No,No,No,Yes,False
8,48330783,Caucasian,Female,[80-90),2,1,4,13,NaN,NaN,...,NaN,No,Steady,No,No,No,Steady,Ch,Yes,False
9,63555939,Caucasian,Female,[90-100),3,3,4,12,NaN,InternalMedicine,...,NaN,No,No,No,No,Steady,Steady,Ch,Yes,False

In [236]:
data.shape

(101766, 30)

In [237]:
data.dropna(inplace=True)

In [238]:
data.shape

(4166, 30)

In [239]:
data.head(10)

,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,...,A1Cresult,metformin,glipizide,glyburide,pioglitazone,rosiglitazone,insulin,change,diabetesMed,readmitted
23879,7239654,Caucasian,Female,[70-80),1,3,6,12,UN,InternalMedicine,...,>8,No,No,No,No,No,Steady,No,Yes,False
24069,14244093,Caucasian,Female,[30-40),1,1,6,13,MC,Nephrology,...,>8,No,No,No,No,No,Steady,No,Yes,False
24117,537543,Caucasian,Female,[30-40),2,1,4,11,MC,Nephrology,...,>8,No,No,No,Steady,No,Steady,Ch,Yes,False
24177,354474,Caucasian,Male,[70-80),2,3,1,12,MC,InternalMedicine,...,>7,No,Down,No,No,No,No,Ch,Yes,False
24228,1186533,AfricanAmerican,Female,[30-40),1,1,6,6,HM,InternalMedicine,...,Norm,No,No,No,No,No,No,No,No,False
24307,4338171,Caucasian,Male,[20-30),1,1,6,2,UN,InternalMedicine,...,>8,No,No,No,No,No,Steady,No,Yes,False
24367,1305612,AfricanAmerican,Female,[70-80),2,3,1,6,MC,InternalMedicine,...,>7,No,No,No,No,No,Steady,No,Yes,False
24386,12089070,Caucasian,Female,[50-60),1,1,6,2,UN,Family/GeneralPractice,...,>8,No,Steady,No,No,Steady,No,Ch,Yes,False
24402,6337395,Caucasian,Female,[40-50),1,1,6,3,MC,InternalMedicine,...,Norm,No,Steady,No,No,No,Steady,Ch,Yes,False
24469,10914048,Caucasian,Male,[20-30),1,1,6,3,UN,InternalMedicine,...,Norm,No,No,No,No,No,Steady,No,Yes,False

In [240]:
numerical_cols = ['time_in_hospital',
'num_lab_procedures',
'num_procedures',
'num_medications',
'number_outpatient',
'number_emergency',
'number_inpatient',
'number_diagnoses']
 
Q1 = data[numerical_cols].quantile(0.25)
Q3 = data[numerical_cols].quantile(0.75)
IQR = Q3 - Q1
 
 
filtered_df = data[~((data[numerical_cols] < (Q1 - 1.5 * IQR)) | (data[numerical_cols] > (Q3 + 1.5 * IQR))).any(axis=1)]

In [241]:
filtered_df.shape

(2417, 30)

In [242]:
output_csv_path = 'cleaned_data.csv'  # You can specify the desired path here

# Write the cleaned DataFrame to a new CSV file
filtered_df.to_csv(output_csv_path, index=False)

print("The cleaned DataFrame has been written to:", output_csv_path)

The cleaned DataFrame has been written to: cleaned_data.csv